services:
  - type: web
    name: montanaro-ou-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard:server --bind 0.0.0.0:$PORT
    envVars:
      - key: RENDER
        value: "true"